import argparse
import math
import os

import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.backends.backend_pdf import PdfPages


def main():
    parser = argparse.ArgumentParser(description="Plot multi-dim-sweep results.")
    parser.add_argument(
        "--time-unit", choices=["steps", "epochs"], default="steps", help="Unit for the targets."
    )
    parser.add_argument("--targets", type=int, nargs="+", default=None, help="Target time points.")
    parser.add_argument(
        "--epoch-tolerance",
        type=int,
        default=10,
        help="Tolerance in epochs for matching logged steps.",
    )
    parser.add_argument(
        "--input",
        type=str,
        default="full.parquet",
        help="Path to the parquet file generated by gather_run_data.py.",
    )
    args = parser.parse_args()

    if args.targets is None:
        args.targets = [30, 300] if args.time_unit == "epochs" else [10000, 150000]

    if not os.path.exists(args.input):
        print(f"Input file {args.input} not found.")
        return

    print(f"Loading data from {args.input}...")
    df = pd.read_parquet(args.input)

    losses_to_plot = ["mse", "cross_entropy"]
    metrics = {
        "Train Accuracy": "eval/train/accuracy",
        "Test Accuracy": "eval/test/accuracy",
        "RNC1 Train": "eval/nc/rnc1/train",
        "RNC1 Test": "eval/nc/rnc1/test",
        "RNC1 Train Mean Test Var": "eval/nc/rnc1_train_mean/test",
        "MIA LFS AUC": "eval/attack/margin_distance_lf/global/auc",
        "MIA LFS TPR@1%": "eval/attack/margin_distance_lf/global/tpr-at-fpr/1",
        "MIA LFS TPR@5%": "eval/attack/margin_distance_lf/global/tpr-at-fpr/5",
        "MIA LFS TPR@10%": "eval/attack/margin_distance_lf/global/tpr-at-fpr/10",
    }

    data = []
    for run_id, run_group in df.groupby("run_id"):
        first_row = run_group.iloc[0]
        run_name = first_row["run_name"]
        loss = "cross_entropy" if "cross_entropy" in run_name else "mse"

        run_dict = {
            "run_id": run_id,
            "loss": loss,
            "dataset_size": first_row["dataset_size"],
            "batch_size": first_row["batch_size"],
            "init_scale": first_row["initialization_scale"],
            "weight_decay": first_row["weight_decay"],
            "metrics": {},
        }

        for m_name, m_key in metrics.items():
            if m_key in run_group.columns:
                valid_rows = run_group.dropna(subset=[m_key])
                if not valid_rows.empty:
                    run_dict["metrics"][m_name] = dict(zip(valid_rows["step"], valid_rows[m_key]))
                else:
                    run_dict["metrics"][m_name] = {}
            else:
                run_dict["metrics"][m_name] = {}

        data.append(run_dict)

    print(f"Loaded metrics for {len(data)} runs.")

    # Standard parameters for Ablation Study and cross-sections
    std_init_scale = 8.0
    std_dataset_size = 1000
    std_weight_decay = 0.001

    def get_vmin_vmax_cmap(m_name):
        if m_name in ["Train Accuracy", "Test Accuracy"] or m_name.startswith("MIA LFS"):
            vmin, vmax = 0.0, 1.0
        elif "RNC1" in m_name:
            vmin, vmax = 0.0, 0.1
        else:
            vmin, vmax = None, None
        cmap = "Blues_r" if "RNC1" in m_name else "Blues"
        return vmin, vmax, cmap

    for loss in losses_to_plot:
        loss_data = [d for d in data if d["loss"] == loss]
        if not loss_data:
            continue

        for target in args.targets:
            unit_str = "epoch" if args.time_unit == "epochs" else "step"
            out_file = f"multi_dim_sweep_{loss}_{unit_str}_{target}.pdf"

            with PdfPages(out_file) as pdf:
                # PAGE 1
                fig, axes = plt.subplots(5, 2, figsize=(14, 30))
                title_unit = "Epoch" if args.time_unit == "epochs" else "Step"
                fig.suptitle(
                    f"Exp: multi-dim-sweep | Loss: {loss.upper()} | {title_unit}: {target} | WD: {std_weight_decay}",
                    fontsize=16,
                )

                p1_data = [d for d in loss_data if d["weight_decay"] == std_weight_decay]

                for idx, (m_name, m_key) in enumerate(metrics.items()):
                    row = idx // 2
                    col = idx % 2
                    ax = axes[row, col]

                    xs, ys, cs = [], [], []
                    for d in p1_data:
                        m_dict = d["metrics"].get(m_name, {})
                        closest_step = None

                        if args.time_unit == "epochs":
                            batches_per_epoch = math.ceil(d["dataset_size"] / d["batch_size"])
                            target_step = target * batches_per_epoch
                            tolerance = args.epoch_tolerance * batches_per_epoch
                        else:
                            target_step = target
                            tolerance = 15000

                        for s in m_dict.keys():
                            if s == target_step:
                                closest_step = s
                                break

                        if closest_step is None:
                            available_steps = list(m_dict.keys())
                            if available_steps:
                                closest = min(available_steps, key=lambda x: abs(x - target_step))
                                if abs(closest - target_step) <= tolerance:
                                    closest_step = closest

                        if closest_step is not None:
                            xs.append(d["dataset_size"])
                            ys.append(d["init_scale"])
                            cs.append(m_dict[closest_step])

                    if xs:
                        vmin, vmax, cmap = get_vmin_vmax_cmap(m_name)
                        sc = ax.scatter(
                            xs,
                            ys,
                            c=cs,
                            cmap=cmap,
                            s=150,
                            edgecolors="k",
                            alpha=0.9,
                            vmin=vmin,
                            vmax=vmax,
                        )
                        ax.set_xscale("log")
                        ax.set_yscale("log", base=2)
                        ax.set_xlabel("Dataset Size")
                        ax.set_ylabel("Init Scale")
                        ax.set_title(f"{m_name}")
                        cbar = plt.colorbar(sc, ax=ax)
                        cbar.set_label(m_name)
                        ax.set_xlim(10, 60000)
                        ax.set_ylim(0.5, 64.0)
                    else:
                        ax.set_title(f"{m_name} (No data near {title_unit.lower()} {target})")

                for idx in range(len(metrics), 10):
                    axes[idx // 2, idx % 2].axis("off")

                plt.tight_layout()
                pdf.savefig(fig)
                plt.close(fig)

                # PAGE 2
                page2_metrics = [
                    "MIA LFS AUC",
                    "Train Accuracy",
                    "Test Accuracy",
                    "RNC1 Train Mean Test Var",
                ]
                fig, axes = plt.subplots(4, 3, figsize=(20, 24))
                fig.suptitle(
                    f"Relations of 3 Variables | Loss: {loss.upper()} | {title_unit}: {target}",
                    fontsize=16,
                )

                for r_idx, m_name in enumerate(page2_metrics):
                    for c_idx in range(3):
                        ax = axes[r_idx, c_idx]
                        xs, ys, cs = [], [], []

                        if c_idx == 0:
                            filtered_data = [
                                d for d in loss_data if d["weight_decay"] == std_weight_decay
                            ]
                            x_key, y_key = "dataset_size", "init_scale"
                            x_label, y_label_text = "Dataset Size", "Init Scale"
                        elif c_idx == 1:
                            filtered_data = [
                                d for d in loss_data if d["init_scale"] == std_init_scale
                            ]
                            x_key, y_key = "dataset_size", "weight_decay"
                            x_label, y_label_text = "Dataset Size", "Weight Decay"
                        else:
                            filtered_data = [
                                d for d in loss_data if d["dataset_size"] == std_dataset_size
                            ]
                            x_key, y_key = "init_scale", "weight_decay"
                            x_label, y_label_text = "Init Scale", "Weight Decay"

                        for d in filtered_data:
                            m_dict = d["metrics"].get(m_name, {})
                            closest_step = None

                            if args.time_unit == "epochs":
                                batches_per_epoch = math.ceil(d["dataset_size"] / d["batch_size"])
                                target_step = target * batches_per_epoch
                                tolerance = args.epoch_tolerance * batches_per_epoch
                            else:
                                target_step = target
                                tolerance = 15000

                            for s in m_dict.keys():
                                if s == target_step:
                                    closest_step = s
                                    break

                            if closest_step is None:
                                available_steps = list(m_dict.keys())
                                if available_steps:
                                    closest = min(
                                        available_steps, key=lambda x: abs(x - target_step)
                                    )
                                    if abs(closest - target_step) <= tolerance:
                                        closest_step = closest

                            if closest_step is not None:
                                xs.append(d[x_key])
                                ys.append(d[y_key])
                                cs.append(m_dict[closest_step])

                        if xs:
                            vmin, vmax, cmap = get_vmin_vmax_cmap(m_name)
                            sc = ax.scatter(
                                xs,
                                ys,
                                c=cs,
                                cmap=cmap,
                                s=150,
                                edgecolors="k",
                                alpha=0.9,
                                vmin=vmin,
                                vmax=vmax,
                            )

                            if x_key == "dataset_size":
                                ax.set_xscale("log")
                                ax.set_xlim(10, 60000)
                            elif x_key == "init_scale":
                                ax.set_xscale("log", base=2)
                                ax.set_xlim(0.5, 64.0)
                            elif x_key == "weight_decay":
                                ax.set_xscale("log")
                                ax.set_xlim(0.00005, 2.0)

                            if y_key == "init_scale":
                                ax.set_yscale("log", base=2)
                                ax.set_ylim(0.5, 64.0)
                            elif y_key == "weight_decay":
                                ax.set_yscale("log")
                                ax.set_ylim(0.00005, 2.0)

                            ax.set_xlabel(x_label)
                            ax.set_ylabel(y_label_text)

                            if r_idx == 0:
                                ax.set_title(f"{x_label} vs {y_label_text}\n{m_name}")
                            else:
                                ax.set_title(f"{m_name}")

                            cbar = plt.colorbar(sc, ax=ax)
                            cbar.set_label(m_name)
                        else:
                            ax.set_title(f"{m_name} (No data)")

                plt.tight_layout()
                pdf.savefig(fig)
                plt.close(fig)

                # PAGE 3
                fig, axes = plt.subplots(len(metrics), 3, figsize=(18, 4 * len(metrics)))
                fig.suptitle(
                    f"Ablation Study Over Time | Loss: {loss.upper()}", fontsize=20, y=0.995
                )

                for r_idx, (m_name, m_key) in enumerate(metrics.items()):
                    for c_idx in range(3):
                        ax = axes[r_idx, c_idx]

                        if c_idx == 0:
                            group_data = [
                                d
                                for d in loss_data
                                if d["init_scale"] == std_init_scale
                                and d["weight_decay"] == std_weight_decay
                            ]
                            group_data.sort(key=lambda x: x["dataset_size"])
                            if r_idx == 0:
                                ax.set_title(
                                    f"Vary Dataset Size\n(IS={std_init_scale}, WD={std_weight_decay})",
                                    fontsize=14,
                                )
                            label_key, label_name = "dataset_size", "DS"
                        elif c_idx == 1:
                            group_data = [
                                d
                                for d in loss_data
                                if d["dataset_size"] == std_dataset_size
                                and d["weight_decay"] == std_weight_decay
                            ]
                            group_data.sort(key=lambda x: x["init_scale"])
                            if r_idx == 0:
                                ax.set_title(
                                    f"Vary Init Scale\n(DS={std_dataset_size}, WD={std_weight_decay})",
                                    fontsize=14,
                                )
                            label_key, label_name = "init_scale", "IS"
                        else:
                            group_data = [
                                d
                                for d in loss_data
                                if d["dataset_size"] == std_dataset_size
                                and d["init_scale"] == std_init_scale
                            ]
                            group_data.sort(key=lambda x: x["weight_decay"])
                            if r_idx == 0:
                                ax.set_title(
                                    f"Vary Weight Decay\n(DS={std_dataset_size}, IS={std_init_scale})",
                                    fontsize=14,
                                )
                            label_key, label_name = "weight_decay", "WD"

                        if len(group_data) > 1:
                            colors = plt.cm.viridis(
                                [i / (len(group_data) - 1) for i in range(len(group_data))]
                            )
                        else:
                            colors = plt.cm.viridis([0])

                        has_data = False
                        for d, c in zip(group_data, colors):
                            m_dict = d["metrics"].get(m_name, {})
                            if m_dict:
                                steps = sorted(m_dict.keys())
                                vals = [m_dict[s] for s in steps]

                                if args.time_unit == "epochs":
                                    batches_per_epoch = math.ceil(
                                        d["dataset_size"] / d["batch_size"]
                                    )
                                    xs = [s / batches_per_epoch for s in steps]
                                else:
                                    xs = steps

                                ax.plot(xs, vals, label=f"{label_name}={d[label_key]}", color=c)
                                has_data = True

                        if has_data:
                            ax.set_xlabel("Epoch" if args.time_unit == "epochs" else "Step")
                            ax.set_ylabel(m_name)
                            ax.legend(fontsize=8, loc="best")
                            vmin, vmax, cmap = get_vmin_vmax_cmap(m_name)
                            if vmin is not None and vmax is not None:
                                ax.set_ylim(vmin, vmax)

                plt.tight_layout(rect=[0, 0, 1, 0.98])
                pdf.savefig(fig)
                plt.close(fig)

            print(f"Saved PDF to {out_file}")


if __name__ == "__main__":
    main()
